### ISSUE TITLE
Webhooks not working

### ISSUE THREAD

**Issue by sergiuv2020** [VectorWatch/Developer-Platform#12]
1. Used the final js code from https://github.com/VectorWatch/Developer-Platform/blob/master/streams/webhooks.js
2. Saved and started the emulator,
3. Also published privatelly and set on watchface
4. Issued curl with the UID
   https://endpoint.vector.watch/VectorCloud/rest/v1/stream/A8F123052CB54C7C43ED83464A48DE9C/webhook?msg=TESTTTT
5. Getting error: {"error":"Remote client not linked"}

**Comment by sergiuv2020** [comment]
Last evening i also got time-out and session not active. Is this feature still în development?

**Comment by bogdanripa** [comment]
Hi there,

This looks like a bug that should be fixed by now. Could you please try this again? I just followed your steps and it worked just fine.

The bug was related to the browser emulator, and would not have reproduced once the stream was published.

**Comment by sergiuv2020** [comment]
Yeyyyy, working now, awesome :)
