### ISSUE TITLE
get config options in config function

### ISSUE THREAD

**Issue by shiftux** [VectorWatch/Developer-Platform#16]
hello
i'd like to get the config options already in the config function. 
something like: 

```
// global vars
var timeDisplay;
var bit;

vectorWatch.on('config', function(event, response) {
    // your stream was just dragged onto a watch face
    logger.info('on config');

    timeDisplay = response.createGridList('Seconds, Minutes, Hours');
    timeDisplay.addOption('seconds');
    timeDisplay.addOption('minutes');
    timeDisplay.addOption('hours');

    timeDisplay = event.getUserSettings().settings['Seconds, Minutes, Hours'].name

    bit = response.createGridList('Which Bit');
    bit.addOption('1');
    bit.addOption('2');
    bit.addOption('4');
    bit.addOption('8');
    bit.addOption('16');
    if (timeDisplay !== 'hours') { bit.addOption('32'); }

    response.send();
});
```

i get errors that the event.getUserSettings object is undefined.
also i can't directly access the timeDisplay variable in this function, it's an object of some sorts, but i can't get the value from it. 

thanks for your help

**Comment by bogdanripa** [comment]
You can do this by marking the 'bit' grid as dynamic, then use the "on options" event to add its values.

Check out this tutorial for a sample:

https://github.com/VectorWatch/Developer-Platform/wiki/Building-a-stream-with-dynamic-configuration-options-(tutorial)
