### ISSUE TITLE
debug on the watch

### ISSUE THREAD

**Issue by shiftux** [VectorWatch/Developer-Platform#18]
hello. 
your tutorial (the hello world part) states this: 

> Please note that we are using vectorWatch.logger.info() instead of console.log() as when this will run in a docker, all the logging will be saved and available for you at a later stage for production debugging purposes. The logger we use has multiple levels, so besides of vectorWatch.logger.info() you can also use vectorWatch.logger.error()

ok, but how can i access that? i would like to debug code on the watch. 
i have a stream that works perfectly fine on the emulator, but produces erroneous output on the watch. 

thanks for your help

**Comment by bogdanripa** [comment]
If you leave the "debugger;" statement in your stream's code and open the developer console, when you refresh your browser the code will run and stop at the debugger line. You can then add breakpoints anywhere in your code and continue running the code.

**Comment by shiftux** [comment]
i understand.
but i would like to debug on the watch, not in the emulator, on the real thing. like i said, the sream worked fine in the emulator, but not on the watch. 
thanks
