### ISSUE TITLE
stream update every second lags

### ISSUE THREAD

**Issue by shiftux** [VectorWatch/Developer-Platform#19]
hello
i followed your tutorial "Building a stream that updates regularly (tutorial)" and took your code in [updating.js](https://github.com/VectorWatch/Developer-Platform/blob/master/streams/updating.js). i adapted it to display the seconds as well and to update every second. i made very minor changes to these 2 functions:

```
function getCurrentTime() {
    var d = new Date();
    return zerofy(d.getHours()) + ':' + zerofy(d.getMinutes()) + ':' + zerofy(d.getSeconds());
}
```

```
function scheduleJob() {
    var scheduleRule = new Schedule.RecurrenceRule();
    scheduleRule.second = new Schedule.Range(0, 59, 1);
    Schedule.scheduleJob(scheduleRule, pushUpdates);
}
```

i then created a custom watch face with a digital time element and an empty stream. after uploading the stream and the watch face i added the stream to the face on the phone. what happens is that the digital time element works fine, but the stream lags behind. it isn't able to update every second and gets behind several seconds every minute and fails to show every second (jumps a few seconds). i assume the method using a scheduleJob takes up too many resources. but since that is what you used in your tutorials i am a little confused. 
is there a way to get the time in a more efficient manner?

thank you for your help

**Comment by shiftux** [comment]
same thing if i remove the seconds and i just go for minutes.
i changed the shedule rule to: `scheduleRule.second = 0;`.
but again updates happen with an incredible delay... after 10 minutes the watch has done 3 updates...
an operation once a minute should not be that resource consuming...?! - what other methods than the node scheduler could i use? - is there no way to access the time from the watch? - i mean the time it displays when i put a normal watch face or a digital time element.

**Comment by bogdanripa** [comment]
Hi Shiftux,

When we send stream updates, we are using the phone's notification system, so it will be pushed as a regular notification to your phone, except that it will not be visible on the phone. It's like a silent notification.

The phone's notification systems should really not be abused, or the phone OS manufacturers might ban the app from sending further notifications for that particular user.

Therefore, our recommendation is for stream updates to be sent at most once every 30 minutes, to avoid any risk.

But thanks for the note, we will take it into account and look for solutions.

**Comment by shiftux** [comment]
thanks @bogdanripa 
but that doesn't really solve my problem. 
if i want to create a stream that shows time, i need it to update every second. 
so is there a way to access the current time on the watch instead of querying if from the phone and thus overloading the phone's notification system? - the watch knows the time. i just need to be able to access it from the stream.
thanks

**Comment by shiftux** [comment]
anything you could add @bogdanripa ?
