### ISSUE TITLE
Hour and Min hands memory size

### ISSUE THREAD

**Issue by emilbrasov** [VectorWatch/Developer-Platform#2]
Hi,
I tried to create some special hour and minute hands, as png files in Gimp. Every time I tried to upload them, I get the same message in the Watch Maker after uploading the first: Size limit reached.
   What is the available memory size for this? I have created a 215 bytes file, and it's still not working.
             Thanks !

**Comment by emilbrasov** [comment]
I tried smaller canvas sizes than 240 x 240. This does not work either. No idea what might be wrong.
One more thing, please make that : "Size limit reached" message more clear, because it's not understandable what it refers to: canvas size, used memory size, something else?

**Comment by bogdanripa** [comment]
Can you pls share the files you try to upload?

**Comment by emilbrasov** [comment]
Sure, here is the first version I tried to upload, than I start cutting canvas size and content, but with same result: image is uploaded fine, I can center the hand, but I can upload another one because I have that error message.
![ceas mistery_min](https://cloud.githubusercontent.com/assets/20880281/17588090/2f5f677e-5fd5-11e6-8e4c-d476a3aa38c3.png)

**Comment by emilbrasov** [comment]
... but I **can't** upload the next one ...

**Comment by emilbrasov** [comment]
The image is white on transparent background, in case you don't see it, it's the white space under my comment from above.

**Comment by emilbrasov** [comment]
![ceas mistery_min](https://cloud.githubusercontent.com/assets/20880281/17909387/f2fda702-698c-11e6-85b6-51e04230560f.png)
here is the file again, please let me know if I'm doing something wrong.

**Comment by emilbrasov** [comment]
Bogdan, did you manage to download the picture? Can I help in any way?

**Comment by radumvlad** [comment]
Hello @emilbrasov, 

In order to use an image hand, please make sure that the image is smaller than 6080 pixels. In other words, multiplying width \* height should have less than 6080 pixels. Also, if the image is close to 6080px you should test it on the watch to be sure everything is good, as there is a bug that may draw you another white line. 

Radu

**Comment by emilbrasov** [comment]
Thanks Radu,
The images are now loaded, but as you said the bug appeared even at 6000 pixels. I could get rid of it at about 5400 pixels per image, which is good enough to try all combinations of hour hands pictures.
