### ISSUE TITLE
Stream text length

### ISSUE THREAD

**Issue by Talkabout** [VectorWatch/Developer-Platform#21]
Hi,

I created my first stream and was a little confused about an obvious limitation of characters. In my case it was only possible to show 13 characters in a stream, everything else was cut off. The stream placeholder was wide enough to show more characters, but the framework seems to limit this.

Is this expected behavior or a bug?

Thanks!

Bye

**Comment by radumvlad** [comment]
Hello again, 

This is a known bug on the browser emulator. However, if you test this by placing the stream on the watch, the input should scroll and show the entire text. 

Thank you for reporting this, we will let you know when we fix it. 

Radu

**Comment by Talkabout** [comment]
Hi,

thanks for the quick response.

But on the watch I am facing this issue also. Why is the text scrolling when there is enough space to show it completely? So the basic question is: is the stream able to show more than 13 characters?

Bye

**Comment by radumvlad** [comment]
Yes, it's not the stream that should take care of the text length, but the textbox from the watchface.

**Comment by Talkabout** [comment]
Ok
