### ISSUE TITLE
Stream not working

### ISSUE THREAD

**Issue by Talkabout** [VectorWatch/Developer-Platform#22]
Hi,

I have created my own stream that is configured to update itself every day (00:00). It shows the current date and the week number. When downloading the stream to the watch an assigning it to a watch face it seems to work fine. But when I try to assign it again after some time the following error is shown:

An error has occurred during communication with the server. ServiceUnavailable

The watch is connected to my mobile phone and everything seems to be fine, still I cannot assign the stream correctly without downloading it again.

I am using a Windows Phone (Windows 10 Mobile).

Bye

**Comment by radumvlad** [comment]
Hello @Talkabout, 

While the stream is private, it only runs in browser. That means that when you close the browser or when the websocket is closed by the server(run button indicates a warning), the stream stops working. 

Once you submit your stream and it gets accepted, it will be separately deployed on our servers and will run continuously. If you still want to test it before submitting to the Vector Store, you can also try to deploy it on another server using the [following tutorial](https://github.com/VectorWatch/Developer-Platform/wiki/Building-a-third-party-stream-using-Heorku-(tutorial)).

Radu

**Comment by Talkabout** [comment]
Hi,

these are bad news... I was hoping that it is also possible to use my private streams with all the needed functionality. Is there a plan to allow this in the future? Because that way your store may get flooded with use case specific streams that are unusable for other users. In my case the stream is not configurable and thus not useful for other people. Submitting it wouldn't make sense...

Bye

**Comment by radumvlad** [comment]
Then you can use the [following tutorial](https://github.com/VectorWatch/Developer-Platform/wiki/Building-a-third-party-stream-using-Heorku-(tutorial)) in order to create a stream that is hosted on another server.

**Comment by Talkabout** [comment]
Ok, got it. Thanks!
