### ISSUE TITLE
Cannot create new faces

### ISSUE THREAD

**Issue by iepster** [VectorWatch/Developer-Platform#6]
While trying to create a new face, there's an error popping up every time reading "Error while creating watchface."

XMLHttpRequest cannot load https://endpoint.vector.watch/VectorCloud/rest/v1/dev/app/save. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://developer.vectorwatch.com' is therefore not allowed access. The response had HTTP status code 500.

I guess you've deployed the dev code on prod.

Hope you'll fix this soon.

**Comment by bogdanripa** [comment]
Fixed!
