### ISSUE TITLE
Error when watch face is published on private

### ISSUE THREAD

**Issue by angheladrianclaudiu** [VectorWatch/Developer-Platform#9]
Hi,

I created and published a new face on private but it isn't showed in the Watch Store. Tried restarting the Iphone app in order to reconnect to server and refresh the data but it didn't worked. Also, it doesn't show the NEW flag in the faces section in Watch Store.

Thank you,
Adrian

**Comment by bogdanripa** [comment]
Can you please share the IRL of the watch face - the one that you see when
editing it?

Thanks!

**Comment by angheladrianclaudiu** [comment]
This is the URL: https://developer.vectorwatch.com/platform/developer/watchface/DBC385AE9A02EF110932364589968356/0

**Comment by angheladrianclaudiu** [comment]
Also, I am seeing now that when I edit the face, the background image doesn't appear. It's like I would start making a new one. The only info that remained it's the one related to Analog Time and Digital Time (in this case I didn't use Streams and Gauges).

**Comment by radumvlad** [comment]
Hello @angheladrianclaudiu, 

You should see your private face now. Can you please check this?
Also, the new flag is available only for public faces unfortunately and we don't currently store your initial background image for dimensions concerns, so you would have to upload it again for a change.

**Comment by angheladrianclaudiu** [comment]
It works. Thank you. 
The new flag is also shown. :)
![rsz_image1](https://cloud.githubusercontent.com/assets/3780416/18348691/839f6378-75d5-11e6-89d3-2070fedceafa.png)
